version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: redis-websocket-server-deno_local
    env_file: .env
    image: dz/redis-websocket-server-deno_local
    ports:
      - 8080:8080
    volumes:
      - .:/app
  redis:
    image: redis:5
    environment:
      ENV: stage
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  redis_data:
